site_name: Tego
site_description: Tego language
site_author: Daniel A. A. Pelsmaeker
site_dir: .docs_site/

repo_url: https://github.com/Virtlink/tego-lang

nav:
  - Home: index.md
  - Getting Started:
    - start/index.md
    - start/releases.md
  - Tutorials:
    - tutorial/index.md
    - Tutorial 1: tutorial/tutorial1.md
  - How-Tos:
    - howto/index.md
  - Reference:
    - reference/index.md
    - reference/modules.md
    - reference/strategies.md
    - reference/java-interop.md
  - Background:
    - background/index.md
  - Develop:
    - develop/index.md
    - Documentation: develop/documentation.md

theme:
  name: material
  language: en
  icon:
    logo: fontawesome/solid/chess-rook
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: blue grey
    accent: orange
  font:
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes    # Insiders only
    - navigation.top
    
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
