site_name: Tego
site_description: Tego language
site_author: Daniel A. A. Pelsmaeker

repo_url: https://github.com/Virtlink/tego-lang
edit_uri: https://github.com/Virtlink/tego-lang/edit/main/docs

nav:
  - Home: index.md
  - Getting Started:
    - start/index.md
    - start/releases.md
  - Tutorials:
    - tutorial/index.md
    - Tutorial 1: tutorial/tutorial1.md
  - How-Tos:
    - howto/index.md
  - Reference:
    - reference/index.md
    - reference/modules.md
    - reference/imports.md
    - reference/declarations.md
    - reference/strategies.md
    - reference/lambdas.md
    - reference/java-interop.md
    - reference/boolean.md
    - reference/build-operator.md
    - reference/match-operator.md
    - reference/congruence-operator.md
    - reference/core.md
    - reference/do-notation.md
    - reference/failure.md
    - reference/functions.md
    - reference/strategy-composition.md
    - IR:
      - reference/ir/index.md
  - Background:
    - background/index.md
    - background/declarations-and-references.md
    - background/lambdas.md
    - background/parameterized-types.md
    - background/semantic-specification.md
    - background/expand-all-predicates.md
    - background/strategy-class.md
  - Develop:
    - develop/index.md
    - develop/milestones.md
    - develop/extract-reference-docs.md
    - Documentation: develop/documentation.md
  - Other:
    - compiler.md
    - continuation-passing-style.md
    - coroutines.md
    - delimited-continuations.md
    - generators.md
    - java-interop.md
    - modifiers.md
    - sequences.md
    - strategies.md

theme:
  name: material
  language: en
  icon:
    logo: fontawesome/solid/chess-rook
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: blue grey
    accent: orange
  font:
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes    # Insiders only
    - navigation.top
    
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date:
      enabled_if_env: CI
  - macros

extra:
  os:
    windows: ":fontawesome-brands-windows: Windows"
    linux: ":fontawesome-brands-linux: Linux"
    macos: ":fontawesome-brands-apple: macOS"
